FROM eclipse-temurin:21-jre

ENV BOT_TOKEN=${BOT_TOKEN}
ENV DATASOURCE_URL=${DATASOURCE_URL}
ENV USERNAME=${USERNAME}
ENV PASSWORD=${PASSWORD}
ENV JWT_KEY=${JWT_KEY}
EXPOSE 8080 5005
WORKDIR /opt/app
COPY app/build/libs/app-2.0.1.jar app.jar
ENTRYPOINT ["java", "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005", "-jar", "app.jar"]
