telegram:
  bot:
    token: ${BOT_TOKEN}
    api: "https://api.telegram.org/"
    timeOutSeconds: 2
  cron:
    #every 2 sec
    longPollingConfiguration: "0/2 * * ? * *"
    #at 8:10 daily
    runReminderConfiguration: "0 10 8 ? * *"
logging:
  level:
    org.springframework.security: DEBUG
    com.example.demo: DEBUG
spring:
  security:
    jwt-secret: ${JWT_KEY}
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  jpa:
    show-sql: true
    generate-ddl: false # Отключаем автоматическую генерацию схемы Hibernate при исп. liquibase
    hibernate:
      ddl-auto: none # Полностью отключаем изменение схемы через Hibernate при исп. liquibase
  datasource:
    url: ${DATASOURCE_URL}
    username: ${USERNAME}
    password: ${PASSWORD}
    driverClassName: org.postgresql.Driver
  sql:
    init:
      platform: postgres
      mode: always # в проде поменять на 'never'

